name: '.NET nanoFramework build components installer'
description: 'Installs the components required to build .NET nanoFramework solutions'
author: '.NET nanoFramework Contributors'
branding:
  icon: git-merge
  color: purple
runs:
  using: 'composite'
  steps:
    - run: '& $env:GITHUB_ACTION_PATH/install-nf-build-components.ps1'
      shell: pwsh
      env:
        GITHUB_AUTH_TOKEN: ${{ inputs.gitHubAuth }}
inputs:
  gitHubAuth:
    required: false
    description: 'GitHub Personal Access Token for accessing GitHub API.'
    default: ''
